# Generated by Django 5.0.3 on 2024-05-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DOCTOR', 'DOCTOR'), ('PATIENT', 'PATIENT'), ('USER', 'USER')], default='USER', max_length=10),
        ),
    ]
