# Generated by Django 5.0.3 on 2024-05-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DOCTOR', 'DOCTOR'), ('PATIENT', 'PATIENT'), ('USER', 'USER'), ('ADMIN', 'ADMIN')], default='USER', max_length=10),
        ),
    ]
