# Generated by Django 5.0.3 on 2024-03-27 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0006_delete_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_beat_audio', models.FileField(upload_to='audio/')),
                ('heart_beat_audio_upload_on', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.patient')),
            ],
        ),
    ]
