# Generated by Django 5.0.3 on 2024-04-07 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_doctor_appointment'),
        ('machine_learning_app', '0003_remove_mldiagnosishistorymodel_prediction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLDiagnosisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_beat_prediction', models.CharField(blank=True, max_length=100, null=True)),
                ('ecg_prediction', models.CharField(blank=True, max_length=100, null=True)),
                ('ucl_prediction', models.CharField(blank=True, max_length=100, null=True)),
                ('heart_beat_prediction_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('ecg_prediction_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('ucl_prediction_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='MLDiagnosisHistoryModel',
        ),
    ]
