# Generated by Django 5.0.3 on 2024-03-27 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0007_doctor_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('code', models.CharField(max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.appointment')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('x-ray', 'x-ray'), ('mri', 'mri'), ('ct-scan', 'ct-scan'), ('ultrasound', 'ultrasound'), ('pet-scan', 'pet-scan'), ('ecg', 'ecg'), ('eeg', 'eeg'), ('ekg', 'ekg'), ('colonoscopy', 'colonoscopy'), ('endoscopy', 'endoscopy'), ('laparoscopy', 'laparoscopy'), ('angiography', 'angiography'), ('mammography', 'mammography'), ('biopsy', 'biopsy'), ('blood-test', 'blood-test'), ('urine-test', 'urine-test'), ('stool-test', 'stool-test'), ('sputum-test', 'sputum-test'), ('biopsy', 'biopsy'), ('bone-scan', 'bone-scan'), ('doppler', 'doppler'), ('echo', 'echo'), ('ekg', 'ekg'), ('emg', 'emg'), ('endoscopy', 'endoscopy'), ('fluoroscopy', 'fluoroscopy'), ('mammography', 'mammography'), ('pet-scan', 'pet-scan'), ('ultrasound', 'ultrasound'), ('x-ray', 'x-ray')], max_length=100)),
                ('image', models.ImageField(upload_to='medical_images/')),
                ('description', models.TextField(blank=True)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.appointment')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.appointment')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.doctor')),
                ('medication_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_data.medication')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.patient')),
            ],
        ),
    ]
