# Generated by Django 5.0.3 on 2024-03-27 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='patient_id',
        ),
    ]
