# Generated by Django 5.0.3 on 2024-03-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_patient_alcoholic_patient_diabetes_patient_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_beat_audio', models.FileField(upload_to='audio/')),
                ('heart_beat_audio_upload_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
