# Generated by Django 5.0.3 on 2024-03-24 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='record_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_app.record'),
        ),
    ]
