# Generated by Django 5.0.3 on 2024-04-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_doctor_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='aboutme',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default='+7 xxx xxx xxxx', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='work_location',
            field=models.CharField(default='National Cardiology Center in Astana', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
