# Generated by Django 5.0.3 on 2024-04-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
