# Generated by Django 5.0.3 on 2024-05-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0022_remove_doctor_height_remove_doctor_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
    ]
