# Generated by Django 5.0.3 on 2024-05-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0023_remove_doctor_first_name_remove_doctor_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
