# Generated by Django 5.0.3 on 2024-05-07 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_remove_appointmentmodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.doctoravailabilitymodel'),
        ),
    ]
