# Generated by Django 5.0.3 on 2024-05-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DOCTOR', 'DOCTOR'), ('USER', 'USER'), ('PATIENT', 'PATIENT')], default=1, max_length=10),
        ),
    ]
