# Generated by Django 5.0.3 on 2024-03-27 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_delete_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('specialization', models.CharField(choices=[('cardiologist', 'cardiologist'), ('dermatologist', 'dermatologist'), ('endocrinologist', 'endocrinologist'), ('gastroenterologist', 'gastroenterologist'), ('nephrologist', 'nephrologist'), ('neurologist', 'neurologist'), ('oncologist', 'oncologist'), ('ophthalmologist', 'ophthalmologist'), ('pediatrician', 'pediatrician'), ('psychiatrist', 'psychiatrist'), ('pulmonologist', 'pulmonologist'), ('radiologist', 'radiologist'), ('rheumatologist', 'rheumatologist'), ('urologist', 'urologist')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.doctor')),
            ],
        ),
    ]
