# Generated by Django 5.0.3 on 2024-04-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_doctor_aboutme_doctor_phone_doctor_work_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='doctor_photos'),
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, upload_to='patient_photos'),
        ),
    ]
