# Generated by Django 5.0.3 on 2024-05-03 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0018_remove_customuser_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='doctor_photos')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('specialization', models.CharField(choices=[('cardiologist', 'cardiologist'), ('dermatologist', 'dermatologist'), ('endocrinologist', 'endocrinologist'), ('gastroenterologist', 'gastroenterologist'), ('nephrologist', 'nephrologist'), ('neurologist', 'neurologist'), ('oncologist', 'oncologist'), ('ophthalmologist', 'ophthalmologist'), ('pediatrician', 'pediatrician'), ('psychiatrist', 'psychiatrist'), ('pulmonologist', 'pulmonologist'), ('radiologist', 'radiologist'), ('rheumatologist', 'rheumatologist'), ('urologist', 'urologist')], max_length=100)),
                ('aboutme', models.TextField(blank=True)),
                ('work_location', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='patient_photos')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('state_id', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('dob', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alcoholic', models.BooleanField(default=False)),
                ('smoker', models.BooleanField(default=False)),
                ('heart_disease', models.BooleanField(default=False)),
                ('hypertension', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.patient')),
            ],
        ),
    ]
