# Generated by Django 5.0.3 on 2024-04-06 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_doctor_appointment'),
        ('machine_learning_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='HeartBeatModel',
        ),
        migrations.RenameField(
            model_name='heartbeatmodel',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.CreateModel(
            name='ECGModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecg_file', models.FileField(upload_to='ecg_files/')),
                ('ecg_file_upload_on', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='UCLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survival', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('pericardialeffusion', models.BooleanField()),
                ('fractionalshortening', models.FloatField()),
                ('epss', models.IntegerField()),
                ('lvdd', models.IntegerField()),
                ('wallmotion_score', models.IntegerField()),
                ('wallmotion_index', models.FloatField()),
                ('mult', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MLDiagnosisHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=100)),
                ('prediction_on', models.DateTimeField(auto_now_add=True)),
                ('ecg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_learning_app.ecgmodel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.patient')),
                ('ucl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_learning_app.uclmodel')),
            ],
        ),
    ]
