# Generated by Django 5.0.3 on 2024-04-07 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning_app', '0004_mldiagnosismodel_delete_mldiagnosishistorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mldiagnosismodel',
            name='ecg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine_learning_app.ecgmodel'),
        ),
        migrations.AddField(
            model_name='mldiagnosismodel',
            name='heart_beat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine_learning_app.heartbeatmodel'),
        ),
        migrations.AddField(
            model_name='mldiagnosismodel',
            name='ucl',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine_learning_app.uclmodel'),
        ),
    ]
