# Generated by Django 5.0.3 on 2024-05-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning_app', '0006_mldiagnosismodel_echo_net_prediction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mldiagnosismodel',
            name='ecg',
        ),
        migrations.RemoveField(
            model_name='echonetmodel',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='mldiagnosismodel',
            name='echo_net',
        ),
        migrations.RemoveField(
            model_name='heartbeatmodel',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='mldiagnosismodel',
            name='heart_beat',
        ),
        migrations.RemoveField(
            model_name='mldiagnosismodel',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='mldiagnosismodel',
            name='ucl',
        ),
        migrations.RemoveField(
            model_name='uclmodel',
            name='patient',
        ),
        migrations.DeleteModel(
            name='ECGModel',
        ),
        migrations.DeleteModel(
            name='EchoNetModel',
        ),
        migrations.DeleteModel(
            name='HeartBeatModel',
        ),
        migrations.DeleteModel(
            name='MLDiagnosisModel',
        ),
        migrations.DeleteModel(
            name='UCLModel',
        ),
    ]
