# Generated by Django 5.0.3 on 2024-05-03 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0019_initial'),
        ('machine_learning_app', '0007_remove_mldiagnosismodel_ecg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECGModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecg_file', models.FileField(upload_to='ecg_files/')),
                ('ecg_file_upload_on', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='EchoNetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('echo_net_file', models.FileField(upload_to='echo_net_files/')),
                ('echo_net_file_upload_on', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HeartBeatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_beat_audio', models.FileField(upload_to='audio/')),
                ('heart_beat_audio_upload_on', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='UCLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survival', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('pericardialeffusion', models.BooleanField()),
                ('fractionalshortening', models.FloatField()),
                ('epss', models.IntegerField()),
                ('lvdd', models.IntegerField()),
                ('wallmotion_score', models.IntegerField()),
                ('wallmotion_index', models.FloatField()),
                ('mult', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MLDiagnosisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_beat_prediction', models.CharField(blank=True, max_length=100, null=True)),
                ('ecg_prediction', models.CharField(blank=True, max_length=100, null=True)),
                ('ucl_prediction', models.CharField(blank=True, max_length=100, null=True)),
                ('echo_net_prediction', models.CharField(blank=True, max_length=100, null=True)),
                ('heart_beat_prediction_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('ecg_prediction_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('ucl_prediction_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('echo_net_prediction_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('ecg', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine_learning_app.ecgmodel')),
                ('echo_net', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine_learning_app.echonetmodel')),
                ('heart_beat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine_learning_app.heartbeatmodel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.patient')),
                ('ucl', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine_learning_app.uclmodel')),
            ],
        ),
    ]
